### ISSUE TITLE
Question!! 

### ISSUE THREAD

**Issue by HERIUN** [ymy-k/Hi-SAM#13]
1. coords are not in [0,1]^2 square.. just coords/img_size(=1024) for normalization(0~1). it is ok?

https://github.com/ymy-k/Hi-SAM/blob/e1ecd86dfcd49202dc369a52e7f1c138d40f1ec4/hi_sam/modeling/prompt_encoder.py#L189

2. in the paper (section 3.5)
"After the final token-to-image
attention, we slice the last three output tokens and get
tˆh out ∈ R
K×3×256."  

but, in the code it looks slice the first three output tokens..  

https://github.com/ymy-k/Hi-SAM/blob/e1ecd86dfcd49202dc369a52e7f1c138d40f1ec4/hi_sam/modeling/mask_decoder.py#L297

3. Why padding needed in prompt encoding??

**Comment by ymy-k** [comment]
1 & 3: These are the default settings in SAM, without modification.
2: The code is about iou tokens but not output tokens
