### ISSUE TITLE
[Question] Line Segmentation Training on Custom Dataset

### ISSUE THREAD

**Issue by VitoVoelker** [ymy-k/Hi-SAM#15]
Hi,

really exited the train code is now released. What would be the best method to train Hi-SAM for line Seg on Custom Datasets ? My First intution would be to convert the custom dataset into the format of the ones given for line seg. The line Segmentation model was trained on ctw1500 and is not included in the data prep guide.Any Ideas on how to custom train Hi-SAM for lien seg ?

Thanks in Advance 
- V

**Comment by ymy-k** [comment]
You can just only use the line annotation to train one output token in the H-Decoder.
