### ISSUE TITLE
请问怎么修改为多类别分割？

### ISSUE THREAD

**Issue by Zeng555** [ymy-k/Hi-SAM#17]
hi-sam如何修改为多类别分割？

**Comment by ymy-k** [comment]
有待探索，还没有尝试过多类别方案

**Comment by zjx1277** [comment]
如果要修改的话，是不是得把高分辨率的mask与低分辨率的mask维度对齐，输出的shape为[batch_size, num_classes, img_h, img_w]?
然后代码的[https://github.com/ymy-k/Hi-SAM/blob/main/hi_sam/modeling/mask_decoder.py#L118](url)
`        masks = masks[:, mask_slice, :, :]
        iou_pred = iou_pred[:, mask_slice]
        hr_masks = hr_masks[:, mask_slice, :, :]
        return masks, hr_masks, iou_pred, iou_pred_hr`
这个地方就不切割了，return出去与labels: [batch_size, num_classes, img_h, img_w]保持维度一致，计算损失。可以这么理吗？

**Comment by ymy-k** [comment]
如果仍然使用point prompt的话，在AMG的时候是可以尝试多类别语义分割，在每一类的结果上取点作point prompt
