### ISSUE TITLE
SAM-TSS (only for text stroke segmentation)这部分image encoder可以使用Efficient Hi-SAM-S么?

### ISSUE THREAD

**Issue by Liupei1101** [ymy-k/Hi-SAM#18]
SAM-TSS (only for text stroke segmentation)可以使用Efficient Hi-SAM-S提升性能么，现在测试有些慢?

**Comment by ymy-k** [comment]
这个模型用的是Efficient SAM初始化训练的，ViT-S backbone虽然快一些但是转化到TSS上性能不是很理想。

**Comment by Liupei1101** [comment]
Thanks for your reply, 接下来你会使用 SAM 2.0 优化你的这项工作么？对视频文字处理会有帮助吧
