### ISSUE TITLE
请问这个方法在中文数据集上的效果如何？

### ISSUE THREAD

**Issue by KQL11** [ymy-k/Hi-SAM#19]
您好！
首先，很感谢作者能开源代码，方法设计也非常有意思。
我这边想询问一下Hi-SAM现有的预训练模型能否直接应用在中文的文本数据集上吗？论文里的结果都是关于英文数据集，所以我想问问中文方面作者有尝试过做一些实验吗？

**Comment by ymy-k** [comment]
之前实验的时候未拿到中文数据集，现有模型不能直接用，text segmentation需要包括中文数据训练

**Comment by KQL11** [comment]
好的，非常感谢！
