### ISSUE TITLE
是否有性能优化的打算？

### ISSUE THREAD

**Issue by compilelife** [ymy-k/Hi-SAM#5]
这是一项很酷的工作，我一直想强化sam的文字分割能力，但没成功，你们做到了！

我利用hi-sam提取mv中的歌词，虽然仍有一些背景像素的干扰，但总体胜过了之前的方法。

只不过目前的速度有些慢，这应该是sam的锅，目前已有很多的工作提升sam的推理速度，很期待hi-sam能变成faster-hi-sam!

一个推理速度足够快的hi-sam能转变为生产就绪的强大基础组件！

**Comment by ymy-k** [comment]
thanks，有空的时候会尝试优化一下
