### ISSUE TITLE
How is output token in Fig3 obtained?

### ISSUE THREAD

**Issue by ShangDongChu** [ymy-k/Hi-SAM#6]
Thanks for your splendid work, but I didn't see any description of how to get the output token before S-Decoder and output tokens before H-Decoder.  The paper says ''Let ts out ∈ R1×256 denote the inherited output token, which is the first slice of SAM’s output tokens.'' but it's still a little ambiguous.

**Comment by ymy-k** [comment]
They are initialized with the output tokens of SAM's mask decoder.
