### ISSUE TITLE
Poor textline detection quality.

### ISSUE THREAD

**Issue by decadance-dance** [ymy-k/Hi-SAM#7]
Hi, first of all, nice job.
I found that quality of the textline detection model is poor. To be more precise, many lines are just not segmented.

To reproduce:
`python demo_text_detection.py --checkpoint pretrained_checkpoint/line_detection_ctw1500.pth --model-type vit_h --input demo/1.jpg --output demo/ --dataset ctw1500`

Images:
![1](https://github.com/ymy-k/Hi-SAM/assets/86170544/5bfbff81-d941-4615-887e-3f863253236d)
![2](https://github.com/ymy-k/Hi-SAM/assets/86170544/0a00846e-f821-46c9-b155-89ac693dcf7f)

Results:
![1](https://github.com/ymy-k/Hi-SAM/assets/86170544/3ad239e9-3fd5-49ce-8094-905e3eeb0981)
![2](https://github.com/ymy-k/Hi-SAM/assets/86170544/78c86dca-e78b-4c06-90b6-b9bf7f938f0a)

**Comment by ymy-k** [comment]
I use demo_amg.py. If you want to use demo_text_detection.py, try to set fg_points_num = 1500, score_thresh = 0.5 as in demo_amg.py.
