### ISSUE TITLE
Poor Paragraph segmentation quality

### ISSUE THREAD

**Issue by SeonjiPark** [ymy-k/Hi-SAM#8]
Hi, thanks for sharing your work. 

By the way, I found your demo_hisam.py shows poor quality.
I tried to use demo_hisam.py following your direction, 

`python demo_hisam.py --checkpoint pretrained_checkpoint/hi_sam_l.pth --model-type vit_l --input demo/2e0cb33320757201.jpg --output demo/ --hier_det`

This is how i executed the your code and i get the result below. 
(Even pretrained weight trained by HierText, which contains input image)
![2e0cb33320757201](https://github.com/ymy-k/Hi-SAM/assets/57519896/8bfb893d-ffe8-45c9-88a7-61ff05b8b0f2)

Could you tell me If I made mistake using demo by any chance ?

**Comment by ymy-k** [comment]
Change the point prompt position in the code.

**Comment by decadance-dance** [comment]
> Change the point prompt position in the code.

How to do that?

**Comment by ymy-k** [comment]
Please see AMG and refer to the paper.
